theme: jekyll-theme-tactile
title: ePortfilo of Pranay Naidu, Southern New Hampshire University
description: The purpose of this site is to showcase and highlight the learnings and enhanced portfolio of prior completed projects.
